//
// Created by xgallom on 4/23/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_EQUATIONS_SIMULATION_DYNAMICS_H
#define POFYZ_2020_LS_ZADANIE_A3_EQUATIONS_SIMULATION_DYNAMICS_H

double K(double x, double integralT);

#endif //POFYZ_2020_LS_ZADANIE_A3_EQUATIONS_SIMULATION_DYNAMICS_H
