//
// Created by xgallom on 3/25/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_DATAFILETABLES_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_DATAFILETABLES_H

#include "dataFiles.h"

#define DATAFILES_DETAILS_DESC  0
#define DATAFILES_DETAILS_COUNT 1

extern const char *DataFilesTable[DATAFILE_COUNT];
extern const char *DataFilesDetailsTable[DATAFILE_COUNT][DATAFILES_DETAILS_COUNT];

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_DATAFILETABLES_H
