//
// Created by xgallom on 4/16/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_INTOPTIONS_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_INTOPTIONS_H

#define INTOPTION_polynomialDegree     0

#define INTOPTION_COUNT   1

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_INTOPTIONS_H
