//
// Created by xgallom on 4/16/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_INTOPTIONTABLES_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_INTOPTIONTABLES_H

#include "intOptions.h"

#define INTOPTIONS_DETAILS_DESC  0
#define INTOPTIONS_DETAILS_COUNT 1

extern const char *IntOptionsTable[INTOPTION_COUNT];
extern const char *IntOptionsDetailsTable[INTOPTION_COUNT][INTOPTIONS_DETAILS_COUNT];

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_INTOPTIONTABLES_H
