//
// Created by xgallom on 4/16/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_OPTIONTABLES_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_OPTIONTABLES_H

#include "options.h"

#define OPTIONS_DETAILS_DESC  0
#define OPTIONS_DETAILS_COUNT 1

extern const char *OptionsTable[OPTION_COUNT];
extern const char *OptionsDetailsTable[OPTION_COUNT][OPTIONS_DETAILS_COUNT];

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_OPTIONTABLES_H
