//
// Created by xgallom on 4/16/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_OPTIONS_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_OPTIONS_H

#define OPTION_polynomialDegree     0

#define OPTION_COUNT   1

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_OPTIONS_H
