//
// Created by xgallom on 5/7/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_PRINTUSAGE_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_PRINTUSAGE_H

void printUsage(void);

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_PRINTUSAGE_H
