//
// Created by xgallom on 3/25/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_STRING_OPTIONS_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_STRING_OPTIONS_H

#define STRINGOPTION_temperature 0
#define STRINGOPTION_name        1
#define STRINGOPTION_COUNT       2

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_STRING_OPTIONS_H
