//
// Created by xgallom on 3/25/20.
//

#ifndef POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_STRINGOPTIONTABLES_H
#define POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_STRINGOPTIONTABLES_H

#include "stringOptions.h"

#define STRINGOPTIONS_DETAILS_DESC  0
#define STRINGOPTIONS_DETAILS_COUNT 1

extern const char *StringOptionsTable[STRINGOPTION_COUNT];
extern const char *StringOptionsDetailsTable[STRINGOPTION_COUNT][STRINGOPTIONS_DETAILS_COUNT];

#endif //POFYZ_2020_LS_ZADANIE_A3_ARGUMENTS_STRINGOPTIONTABLES_H
